<?php
///CAUSEHUB INFO START
	
	define(CAUSEHUB_VERSION_NAME, 'Alpha');
	define(CAUSEHUB_VERSION_MAJOR, '1');
	define(CAUSEHUB_VERSION_MINOR, '1');
	define(CAUSEHUB_VERSION_VERSION, '1');
	define(CAUSEHUB_VERSION_BUILD, '12c');
	define(CAUSEHUB_VERSION, CAUSEHUB_VERSION_NAME.' '.CAUSEHUB_VERSION_MAJOR.'.'.CAUSEHUB_VERSION_MINOR.'.'.CAUSEHUB_VERSION_VERSION.'.'.CAUSEHUB_VERSION_BUILD.'');

///CAUSEHUB INFO END
?>
